### PR TITLE
Empty line convention for multi-line blocks changed.

### PR DESCRIPTION
**Pull request by jonathan-jaekel**
I think what we want is:
```ruby
describe Core::Enum do
  context '#initialize' do
    it 'Return an enum instance for an existing constant' do
      expect(ExampleEnum::ONE.class.superclass).to be_a ExampleEnum.class
    end

    it 'Raise an error for an not existing constant' do
      expect { ExampleEnum::X }.to raise_error(ArgumentError, 'ENUM X not found')
    end
  end
end
```

But the convention says:
```ruby
describe Core::Enum do

  context '#initialize' do

    it 'Return an enum instance for an existing constant' do
      expect(ExampleEnum::ONE.class.superclass).to be_a ExampleEnum.class
    end

    it 'Raise an error for an not existing constant' do
      expect { ExampleEnum::X }.to raise_error(ArgumentError, 'ENUM X not found')
    end

  end

end
```

### CODE REVIEW

**Comment by sfroehler** [comment]
Agreed.

any other opinions? @skorbut @sthollmann @acwebionate @jannik-hh @jungbunzlav

**Comment by acwebionate** [comment]
Option 1 :+1:

**Comment by sthollmann** [comment]
:+1:

**Comment by jannik-hh** [comment]
:+1

**Comment by jungbunzlav** [comment]
:+1:

**Comment by sfroehler** [comment]
PR has been open for 7 days and everybody had a fair chance to intervene. Feel free to merge.

**Pull request merged**
