### PR TITLE
Set line length convention to 100 chars.

### PR DESCRIPTION
**Pull request by jonathan-jaekel**
Line breaks should be for semantic reasons less for style reasons. To short line
lengths destroys the semantic expressiveness and makes the code harder to read.

Why?
- The 80 chars per line convention comes from punched cards. Well, for
  historical reasons... Anyone still use punched cards?
- OK, there must be some other good reasons. The VT 100 DEC video terminal shows
  80 chars per line. Anyone still use this?
- More than 80 chars could not be printed on a A4 letter. Save the trees!

What limits the line length today?
- GitHubs file view is able to show ~125 chars without horizontal scrolling. The
  exact length depends from OS, browser, font type. 120 chars should be save.
  See http://stackoverflow.com/questions/22207920/what-is-githubs-character-limit-or-line-length-for-viewing-files-on-github
  Any reasons why GitHub doesn't use responsive design?
- Atom editor on screens with retina display (1920px) or external monitor
  (2560px) is able to show more than 120 chars per line. Even with visible tree
  view and line numbers. To show tree view and two horizontal split panels on
  retina display you have to decrease the font size from 16pt to 14pt to have
  still 100 chars per line visible.

So 100 chars per line should fit any reasonable use case. 20 chars more helps a
lot to keep the sources readable.

See: http://hilton.org.uk/blog/source-code-line-length

### CODE REVIEW

**Comment by sfroehler** [comment]
@webionate/developer any opinions on this?

**Comment by acwebionate** [comment]
Phew. I'd prefer the 80 char limit, but for sentimental reasons :sob: 
Our code atm is a mixture of 80 chars and "as long as it gets".

**Comment by sfroehler** [comment]
As I often work with a horizontal splitscreen setup I kind of prefer the 80 character limit. And it seems that it still is the de facto standard. 
But @jonathan-jaekel made some good points and as I tend to use rather long method and attribute names I already felt the pain of multiple line breaks multiple times. So I would grumblingly agree to this change. ;)

**Comment by jannik-hh** [comment]
:+1:

**Comment by sthollmann** [comment]
I usually don't work in a split screen-setup, so for me, the Github.com diff view is the most relevant here.

If you use line comments in the context of a PR, the diff "window" get's pretty narrow (~80 chars):

bildschirmfoto 2015-04-23 um 14 54 51

But if I have to decide between reasonable, multi-lin code formatting, and the luxury to be able to view diffs on line comments without the need for horizontal scrolling - I choose the former.

So, 100 chars is :+1: with me.

**Comment by sfroehler** [comment]
@jonathan-jaekel we have rubocop.yml in the guides. Would you mind adding the change for the LineLength Cop to this PR?
https://github.com/webionate/guides/blob/master/style/rubocop/.rubocop.yml#L133

**Comment by jonathan-jaekel** [comment]
@sthollmann I don't know why GitHub doesn't use responsive design... Maybe there is an CSS hack?
@sfroehler Done.

**Comment by sfroehler** [comment]
Thank you, @jonathan-jaekel 

PR has been open for 7 days and everybody had a fair chance to intervene. Feel free to merge.

**Pull request merged**
